name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  PlanetScale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
        # Number of commits to fetch. 0 indicates all history for all branches and tags.
        # Default: 1
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.4
        with:
          files: |
            prisma/schema.prisma
      
      - name: List all modified files
        run: |
          echo ${{ steps.changed-files-specific.outputs.any_changed }}

      - uses: mohsen1/planetscale-prisma-github-action@main
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        with:
          database: github-actions
          organization: mohsen
          planetscale-service-token-id: hucnq9p853sq
          planetscale-service-token: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
